import { Project } from '@/types'

export const projects: Project[] = [
  {
    id: '1',
    slug: 'digital-memory-archive',
    title: 'Digital Memory Archive',
    description: 'An interactive installation exploring personal and collective memory through digital artifacts and physical objects.',
    longDescription: 'Digital Memory Archive is an immersive installation that investigates the relationship between digital preservation and material memory. Through a combination of projected imagery, physical artifacts, and interactive elements, the work creates a contemplative space for examining how we remember and forget in the digital age. The installation uses real-time data processing to transform visitor interactions into visual narratives, creating a unique experience for each participant.',
    tags: ['Installation', 'Digital Media', 'Interactive', 'Projection Mapping'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1800',
    images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1800',
      'https://images.unsplash.com/photo-1618556450994-a6a128ef0d9d?w=1800',
      'https://images.unsplash.com/photo-1618556450991-2f1af64e8191?w=1800',
      'https://images.unsplash.com/photo-1618556450993-c2c27c7a0f8e?w=1800',
    ],
    year: '2024',
    client: 'Independent Project',
    role: 'Lead Artist & Creative Director',
  },
  {
    id: '2',
    slug: 'liminal-spaces',
    title: 'Liminal Spaces',
    description: 'A series of digital compositions examining transitional states and threshold experiences.',
    longDescription: 'Liminal Spaces is a body of work that explores the concept of in-between states through digital composition and generative processes. The series investigates moments of transition, uncertainty, and transformation, creating visual experiences that exist between defined categories. Each piece utilizes custom algorithms to generate unique compositions that evoke the feeling of being in transit—neither here nor there, but somewhere in between. The work has been exhibited internationally and collected as NFTs.',
    tags: ['Digital Art', 'Generative', 'Series', 'NFT'],
    image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1800',
    images: [
      'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1800',
      'https://images.unsplash.com/photo-1634017839045-cdae4d26ab76?w=1800',
      'https://images.unsplash.com/photo-1634017838951-3c6f9c62e2cc?w=1800',
      'https://images.unsplash.com/photo-1634017838514-5aa22f0c9f51?w=1800',
    ],
    year: '2024',
    client: 'Various Collectors',
    role: 'Artist & Developer',
  },
  {
    id: '3',
    slug: 'technological-meditations',
    title: 'Technological Meditations',
    description: 'A multimedia installation addressing our relationship with technology and contemplative practices.',
    longDescription: 'Technological Meditations creates an environment that juxtaposes digital interfaces with spaces for quiet reflection. The installation invites visitors to consider how technology shapes our capacity for attention, presence, and meditative states in contemporary life. Through a carefully orchestrated combination of sound, light, and interactive elements, the work guides participants through a journey of digital disconnection and mindful reconnection. Commissioned for the 2023 Digital Arts Festival.',
    tags: ['Installation', 'Multimedia', 'Sound', 'Interactive'],
    image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1800',
    images: [
      'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1800',
      'https://images.unsplash.com/photo-1558655146-d09347e92766?w=1800',
      'https://images.unsplash.com/photo-1558655146-56750cb5e3f0?w=1800',
      'https://images.unsplash.com/photo-1558655146-364adec68144?w=1800',
    ],
    year: '2023',
    client: 'Digital Arts Festival',
    role: 'Installation Artist',
  },
  {
    id: '4',
    slug: 'identity-protocols',
    title: 'Identity Protocols',
    description: 'An exploration of identity construction in networked environments through code and visual systems.',
    longDescription: 'Identity Protocols examines how identity is constructed, performed, and validated in digital networks. Using custom software and visual systems, the work reveals the protocols and infrastructures that mediate contemporary identity formation. The project combines data visualization, real-time network analysis, and interactive experiences to make visible the invisible systems that shape our digital selves. Featured in exhibitions exploring the intersection of technology and society.',
    tags: ['Code Art', 'Digital Identity', 'Systems', 'Web-based'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1800',
    images: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1800',
      'https://images.unsplash.com/photo-1551288049-19c5f4b5b3b7?w=1800',
      'https://images.unsplash.com/photo-1551288049-23da55b58a63?w=1800',
      'https://images.unsplash.com/photo-1551288049-1a2e6b930a1e?w=1800',
    ],
    year: '2023',
    client: 'Independent Research',
    role: 'Artist & Software Developer',
  },
]
